import { SubmissionStream } from "snoostorm";
import Snoowrap from "snoowrap";
import 'dotenv/config'

const credentials = {
    "userAgent":    "automod-OPTN-bot:v0.0.3",
    "clientId":     process.env.CLIENT_ID,
    "clientSecret": process.env.CLIENT_SECRET,
    "username":     process.env.USERNAME,
    "password":     process.env.PASSWORD
}

const data = {
    "fancyPantsTag": "Formatted text generated by the [<a href=\"https://OPTN.club\">OPTN.club</a> Tune Formatter](<a href=\"https://optn.club/formatter\">https://optn.club/formatter</a>)",
    "tuneFormatterTag": "Formatted text generated by the <a href=\"https://optn.club/formatter\">OPTN.club Tune Formatter</a>",
    "staticMessage": "*Come join the [OPTN Discord server!](https://discord.gg/OPTN) Once you get in, be sure to visit the Rules-and-Roles channel and pick up the Forza Horizon role there to unlock the channels specific to FH5.*\n",
    "fancyPantsWarning": "**Oh no! You posted in Fancy Pants Editor mode. To make sure your tune is formatted correctly, please edit your post and switch to Markdown mode. You should see \"Switch to markdown Mode\" on the right side of the textbox navbar.** \n\n",
    "tuneFormatterText": "**Thank you for using the OPTN tune formatter! Report any bugs or issues on the OPTN-Club github, or message one of the admins.** \n\n",
    "footer": "***\n^Visit ^https://optn.club/ ^for ^a ^tune ^formatter, ^tune ^calculator, ^and ^tuning ^guide."
}

const client = new Snoowrap(credentials)

const BOT_START = Date.now() / 1000
const forzaOpenTunes = { subreddit: "ForzaOpenTunes", limit: 100, pollTime: 10000 }

new SubmissionStream(client, forzaOpenTunes).on('item', (post) => {
    let messageType = ""
    if (post.created_utc < BOT_START) return
    if (post.selftext_html.includes(data.fancyPantsTag)) {
        console.log("Fancypants text detected.")
        messageType = data.fancyPantsWarning
    } else if (post.selftext_html.includes(data.tuneFormatterTag)) {
        console.log("Good tune detected.")
        messageType = data.tuneFormatterText
    }
    post.reply(`${messageType}${data.staticMessage}${data.footer}`)
    console.log(post)
})

// const getAutoReply = async () => {
//     let data = "(Empty data)"
//     try {
//         const response = await fetch('https://raw.githubusercontent.com/OPTN-Club/OPTN-reddit-bot/main/auto_reply_post.txt')
//         if (!response.ok) {
//             throw (new Error(`${response.status} (${response.statusText})`))
//         }
//         data = await response.text()
//     } catch (error) {
//         console.error(`Error in fetch: ${error.message}`)
//     }
//     return data
// }


// let savedFancyPantsPosts = ["whbc4b"]

// setInterval(() => {
//     for (let postId of savedFancyPantsPosts) {
//         const submission = client.getSubmission(postId)
//         submission.selftext_html.then(function (postBody) {
//             if (postBody !== null && submission.edited &&
//                 postBody.includes("<p><a href=\"https://optn.club/formatter\">View this tune on optn.club</a></p>")) {
//                 console.log("Fixed!")
//             } else {
//                 console.log("Unfixed.")
//             }
//         })
//     }
// }, 10000)